config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'

  # webhooks
  post '/webhooks/uninstall', :to => "webhook_manager#uninstall"
  post '/webhooks/order/create', :to => "webhook_manager#order_create"
  get '/settings' , :to => "home#settings", :as => "settings"
  patch '/settings/save_token', :to => "home#save_token", :as => "save_token"
  get '/settings/save_token', :to => "home#save_token"
  post '/home/signup', :to => "home#signup", :as => "create_account"
  get '/product/image/:id', :to => "product#choose_image", :as => "choose_image"
  get '/product/image_url/:id', :to => "product#enter_image_url", :as => "enter_image_url"
  post '/product/image/save', :to => "product#save_image", :as => "save_image"
  # get '/add/product', :to => "product#add", :as => "add_product"
  # post '/add/product', :to => "product#save_product"
  get '/remove/product/:id', :to => "product#remove", :as => "remove_product"
  get '/refresh', :to => "home#refresh_products", :as => "refresh_products"



  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController
  def index
    @thisshop = Shop.find_by_shopify_domain current_shopify_domain
    @filteredProd = @thisshop.products.reverse

    @signup = false
    if @thisshop.printex_token == nil || @thisshop.printex_token == ""
      @signup = true
    end

  end

  def signup
    @thisshop = Shop.find_by_shopify_domain current_shopify_domain
    puts "**********"
    puts "**********"
    puts "**********"

    acc =  account_params

    @account = {
      :name => acc["name"],
      :owner_name => acc["owner_name"],
      :email => acc["email"],
      :phone_number => acc["phone_number"],
      :payment_email => acc["email"],
      :international => acc[:international],
      :web_address => @thisshop.shopify_domain,
      :username => acc[:username],
      :password => acc[:password],
      :from_name => acc[:from_name],
      :from_email => acc[:from_email],
      :copy_customer => acc[:copy_customer],
      :copy_email => acc[:copy_email]
    }

    require 'net/http'
    require 'uri'
    require 'json'

    uri = URI.parse("http://dev.lockerstock.printexinc.com/")
    # Create the HTTP objects
    http = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Post.new("/api/account")
    request.basic_auth "shopify", 'Ex1hDXNhJMH7bLTxtRqe'
    request.body = @account.to_query

    # Send the request
    response = http.request(request)

    res = JSON.parse(response.body)

    puts res.inspect
    puts res["message"]
    puts response.code
    @message = res["message"].gsub('\n', '');
    puts @message
    if response.code != "200"
      respond_to do |format|
        format.js{
          render :partial => "home/signup", :locals => {:message => @message }, :status => 200
        }
      end
    else
      @thisshop.printex_token = res["api_token"]
      @thisshop.username = acc["username"]
      @thisshop.password = acc["password"]
      @thisshop.save
      redirect_to :action => "index"
    end
  end

  def account_params
    params.require(:account).permit!
  end

  def refresh_products
    @products = []
    (1..pages).each do |page|
      @products += ShopifyAPI::Product.all(params: { page: page, limit: PER_PAGE })
    end

    @thisshop = Shop.find_by_shopify_domain current_shopify_domain

    @filteredProd = []
    @products.each do |product|
      vendor = product.vendor.downcase
      @filteredProd << product if vendor == "printex"
    end

    for product in @filteredProd
      save_product_in_db( product, @thisshop)
    end

    redirect_to :action => "index"
    return
  end

  def save_product_in_db( product, shop)
    p = Product.new
    p.title = product.title
    p.product_id = product.id
    p.shop = shop
    p.save
  end

  def settings
    # @thisshop = Shop.find_by_shopify_domain current_shopify_domain
    @thisshop = Shop.find_by_shopify_domain current_shopify_domain
    puts @thisshop.inspect
  end

  def save_settings
    # s = params.require(:shop).permit!
    # puts "sss 88* ** ** ** ** * ** "
    # puts s.inspect
    # @newtoken = s[:shop][:printex_token]
    # @thisshop.printex_token = @newtoken
    # @thisshop.save

    # redirect_to :action => "settings"
  end
  def save_token
    @thisshop = Shop.find_by_shopify_domain current_shopify_domain
    parameters = params.permit(:printex_token)
    @thisshop.printex_token = parameters[:printex_token]

    @show_notification = true if @thisshop.save

    flash[:notice] = "API Token saved successfully"
    redirect_to :settings
    return
  end

  private

  PER_PAGE = 200
  # calculates total number of pages required
  def pages
    count = ShopifyAPI::Product.count
    return 1 if count.zero?

    div, mod = count.divmod(PER_PAGE)
    if div.zero?
      1
    elsif mod > 0
      div + 1
    else
      div
    end
  end
  def settings_params
    # params.require(:shop).permit!
  end
end

app/views/home/_signup.js.erb
<%= puts "from sig" %>
var msg = "<%= raw @message.gsub("\n"," ") %>";
ShopifyApp.flashError(msg);

app/views/home/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: "Home",
        buttons: {
          primary: {
            label: 'Settings',
            href: "/settings"
          }
        }
      });
    });
  </script>
<% end %>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12" style="margin-top:20px;">
      <% if @signup == false %>
      <div class="panel panel-default">
        <div class="panel-heading">All Products</div>
        <div class="panel-body">
          <a href="<%= refresh_products_path %>" class="with-icon btn btn-warning">
            <i class='fa fa-refresh'></i>Refresh
          </a>
          <br>
          <div class="table-responsive">
            <table class="table table-bordered products-table">
              <thead>
                <tr>
                  <th class="no">#</th>
                  <th>Title</th>
                  <th class="art-image">Art Image</th>
                  <th class="remove">Remove</th>
                </tr>
              </thead>
              <tbody>
                <% i = 1 %>
                <% @filteredProd.each do |product| %>
                <tr class="product-<%= product.id %>">
                  <td class="no">
                    <%= i %>
                  </td>
                  <td>
                     <%= link_to product.title, "https://#{@shop_session.url}/admin/products/#{product.product_id}", :target => "_blank" %>
                  </td>
                  <td class="">
                    <div class="product-image-thumbnail image-<%= product.id %> <%= 'hidden' if product.image == nil %>">
                      <img src="<%= product.image %>" alt="" class="img-thumbnail">
                    </div>
                    <% if product.image == nil %>
                      <span class="text-danger">No image choosen</span>
                    <% else %>
                    <% end %>
                    <button class="btn btn-info chooseImage" data-id="<%= product.product_id %>"><% if product.image == nil %>Choose Image <% else %>Change Image<% end %></button>
                    <button class="btn btn-info choooseImageURL" data-id="<%= product.product_id %>"><% if product.image == nil %>Image From URL <% else %>Image From URL<% end %></button>
                  </td>
                  <td class="remove">
                    <a href="<%= remove_product_path product.id %>" data-remote="true" data-confirm="Are you sure, you want to delete this product from app database?"><i class="fa fa-times"></i></a>
                  </td>
                </tr>
                <% i = i + 1 %>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="clearfix">

          </div>
        </div>
      </div>
      <% else %>

      <div class="alert alert-primary">
        Sign up for a printex account by clicking the button below
      </div>
      <div class="alert alert-info">
        If you already have a printex account then navigation to settings to add your api token
      </div>
      <div class="text-center">
        <button type="button" class="btn btn-lg btn-info" data-toggle="modal" data-target="#signUpModal">
          Create Account
        </button>
      </div>
      <% end %>
    </div>
    <div class="col-xs-12">
      <div class="alert alert-info" role="alert">
        <b>Note:  </b>After adding the product in store, you should choose an image here which will be sent over to printex to print on the product
      </div>
      <div class="alert alert-info">
        If you don't see newly added product here. Click on <b>Refresh</b> button
      </div>
      <div class="alert alert-primary" role="alert">
        <b>Note:  </b>Deleting the products in the application will not delete the product from your store. It will just remove the product information from Application's database.
      </div>
    </div>
  </div>
</div>


<!-- Signup Modal -->
<div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="signUpModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="signUpModalLabel">Sign Up</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="<%= create_account_path %>" method="POST" class="clearfix" data-remote="true">
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <label for="account[name]" class="bmd-label-floating">Name *</label>
              <input type="text" name="account[name]" id="account[name]" placeholder="Account/Company name" class="form-control" required="required">
            </div>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <label for="account[owner_name]" class="control-label">Owner Name</label>
              <input type="text" name="account[owner_name]" id="account[owner_name]" placeholder="(Optional)" class="form-control">
            </div>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <label for="account[email]" class="control-label">Email *</label>
              <input type="email" name="account[email]" id="account[email]" placeholder="abc@xyz.com" class="form-control" required="required">
            </div>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <label for="account[phone_number]" class="control-label">Phone *</label>
              <input type="tel" name="account[phone_number]" id="account[phone_number]" placeholder="(Optional)" class="form-control">
            </div>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <label for="account[payment_email]" class="control-label">Payment Email </label>
              <input type="email" name="account[payment_email]" id="account[payment_email]" placeholder="abc@xyz.com" class="form-control">
              <span class="help-block">
                Email address to receive Payment invoices to
              </span>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <label for="account[international]" class="control-label">International *</label>
              <select name="account[international]" id="account[international]" class="form-control">
                <option value="0">Inside US</option>
                <option value="1" selected="selected">Outside US</option>
              </select>
            </div>
          </div>
          <hr class="col-xs-12">
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <label for="account[username]" class="control-label">Username *</label>
              <input type="text" name="account[username]" placeholder="Create Username" id="account[username]" class="form-control" />
            </div>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <label for="account[password]" class="control-label">Password *</label>
              <input type="password" name="account[password]" placeholder="Create password" id="account[password]" class="form-control" />
            </div>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <label for="account[web_address]" class="control-label">Store URI *</label>
              <input type="url" name="account[web_address]" value="<%= @thisshop.shopify_domain %>" disabled="disabled" id="account[web_address]" class="form-control" required="required" />
            </div>
          </div>
          <hr class="col-xs-12">
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <label for="account[from_name]" class="control-label">From Name</label>
              <input type="text" name="account[from_name]" placeholder="Name" id="account[from_name]" class="form-control" />
              <span class="help-block">Name that tracking emails come from</span>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <label for="account[from_email]" class="control-label">From Email</label>
              <input type="email" name="account[from_email]" placeholder="Email" id="account[from_email]" class="form-control" />
              <span class="help-block">Email address that tracking emails come from</span>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <label for="account[copy_customer]" class="control-label">Copy customer</label>
              <select name="account[copy_customer]" id="account[copy_customer]" class="form-control" >
                <option value=""></option>
                <option value="1">Yes</option>
                <option value="0">No</option>
              </select>
              <span class="help-block">Set yes to have copy of tracking number email sent to <b>Copy email</b></span>
            </div>
          </div>
          <div class="col-xs-12 col-sm-6">
            <div class="form-group">
              <label for="account[copy_email]" class="control-label">Copy Email</label>
              <input type="email" name="account[copy_email]" placeholder="Email" id="account[copy_email]" class="form-control" />
              <span class="help-block">Email address that is copied on tracking</span>
            </div>
          </div>
          <hr class="col-xs-12">
          <div class="col-xs-12">
            <div class="form-group">
              <button type="submit" class="btn btn-info pull-right">Create Account</button>
            </div>
          </div>
        </form>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>

app/views/home/settings.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: "Settings",
        buttons: {
          primary: {
            label: 'Home',
            href: "/"
          }
        }
      });
    });
  </script>
<% end %>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <div class="panel panel-primary">
        <div class="panel-heading">Printex API Token</div>
        <div class="panel-body">
          <%= form_tag save_token_path,:method => :PATCH do |f| %>
          <div class="form-group">
            <%= text_field_tag :printex_token, @thisshop[:printex_token] ,:class => "form-control" %>
          </div>
          <div class="form-group">
            <%= submit_tag :Save , :class => "btn btn-success" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<% if @show_notification %>
<script>
  $(document).on("turbolinks:load",function(){
    ShopifyApp.flashNotice("API Token saved successfully");
  });
</script>
<% end %>