config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'

  # webhooks
  post '/webhooks/uninstall', :to => "webhook_manager#uninstall"
  post '/webhooks/order/create', :to => "webhook_manager#order_create"
  get '/settings' , :to => "home#settings", :as => "settings"
  patch '/settings/save_token', :to => "home#save_token", :as => "save_token"
  get '/settings/save_token', :to => "home#save_token"
  post '/home/signup', :to => "home#signup", :as => "create_account"
  get '/product/image/:id', :to => "product#choose_image", :as => "choose_image"
  get '/product/image_url/:id', :to => "product#enter_image_url", :as => "enter_image_url"
  post '/product/image/save', :to => "product#save_image", :as => "save_image"
  # get '/add/product', :to => "product#add", :as => "add_product"
  # post '/add/product', :to => "product#save_product"
  get '/remove/product/:id', :to => "product#remove", :as => "remove_product"
  get '/refresh', :to => "home#refresh_products", :as => "refresh_products"



  mount ShopifyApp::Engine, at: '/'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	
  belongs_to :shop

  validates :product_id,
            :uniqueness => true,
            :presence => true


end

app/controllers/product_controller.rb
class ProductController < ShopifyApp::AuthenticatedController
  def add
    @thisshop = ShopifyAPI::Shop.current
  end

  def save_product
    d = product_params
    product_images = []
    if d["product_image"] != nil
      d["product_image"].each do |key,image|
        im = {}
        im[:src] = image
        product_images << im if image != ""
      end
    end
    # doing shopify api call to create a product
    product = ShopifyAPI::Product.new
    product.title = d["product_title"]
    product.vendor = d["product_vendor"]
    product.product_type = d["product_type"]
    product.body_html = d["product_description"]
    product.images = product_images
    product.options = []
    product.variants = []

    if d[:product_variant] != nil
      # product options
      options_count = 0;
      d["product_options"].each do |key,option|
        if option != ""
          product.options << {:name => option}
          options_count = options_count + 1
        end
      end
      puts product.options.inspect

      # add product variants
      d[:product_variant].each do |key, variant|
        thisvariant = {}
        # thisvariant[:title] = "#{variant[:option_1]} #{variant[:option_2]} #{variant[:option_3]}"
        thisvariant[:option1] = variant[:option_1] if variant[:option_1] != nil
        thisvariant[:option2] = variant[:option_2] if variant[:option_2] != nil
        thisvariant[:option3] = variant[:option_3] if variant[:option_3] != nil
        thisvariant[:price] = variant[:price]
        thisvariant[:compare_at_price] = variant[:compare_at_price]

        product.variants << thisvariant
      end
    end

    product.save

    # if no product variant then default variant
    if d[:product_variant] == nil
      default_variant = product.variants.first
      default_variant.price = d[:product_price]
      default_variant.compare_at_price = d[:product_compare_price]
    end

    # adding product for printex
    product.add_metafield(ShopifyAPI::Metafield.new({
       :description => 'Printex Product',
       :namespace => 'printex',
       :key => 'is_printex',
       :value => 1,
       :value_type => 'integer'
    }));

    product.save

    # adding product to database
    @thisshop = Shop.find_by_shopify_domain current_shopify_domain
    p = Product.new
    p.title = product.title
    p.product_id = product.id
    p.shop = @thisshop
    p.save

    flash[:notice] = "Product added successfully"
    redirect_to :controller => "home", :action => "index"
    return
  end

  def remove
    respond_to do |format|
      format.js {
        p = params.permit(:id)
        @classid = p[:id]
        shop = Shop.find_by_shopify_domain current_shopify_domain
        product = shop.products.find(p[:id])
        # sproduct = ShopifyAPI::Product.delete(product.product_id)
        product.destroy
      }
     end
  end

  def product_params
    params.permit(
      :product_title,
      :product_description,
      :product_vendor,
      :product_type,
      :product_price,
      :product_compare_price,
      :product_image => {},
      :product_options => {},
      :product_variant => {}
    )
  end

  def choose_image
    @product = ShopifyAPI::Product.find(params[:id])
  end
  def enter_image_url
    @product = ShopifyAPI::Product.find(params[:id])
    @product_db = Product.where(:product_id => @product.id)
    @image = @product_db.first.image
    puts @image;
    puts @product_db.inspect;
  end
  def save_image
    respond_to do |format|
      format.js {
        pid = params["product_id"]
        image_src = params["image_src"]

        @product = Product.find_by_product_id(pid)
        @product.image = image_src if image_src != ""
        @product.save
        @success = true if image_src != ""
        puts "saving image for #{pid}"
      }
    end
  end
end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/product/add.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize({
        title: "Add a new Product",
        buttons: {
          primary: {
            label: 'Home',
            href: "/"
          },
          secondary: {
            label: 'Settings',
            href: "/settings"
          }
        }
      });
    });
  </script>
<% end %>
<div class="container-fluid">
  <div class="row">
  <%= form_tag add_product_path, :multipart => true, :method => :POST, :class => "form-horizontal" do %>
    <div class="col-xs-12" style="margin-top:20px;">
      <div class="panel panel-info">
        <div class="panel-heading">Basic Info <a href="/add/product">Add Product</a></div>
        <div class="panel-body">
          <div class="form-group">
            <%= label_tag :product_title, "Title", :class => "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= text_field_tag :product_title,nil, :class => "form-control", :required => true %>
            </div>
          </div>
          <div class="form-group">
            <%= label_tag :product_description, "Description", :class => "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= text_area_tag :product_description,nil, :row => 15, :class => "form-control tinymce" %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="panel panel-info">
        <div class="panel-heading">Product Info</div>
        <div class="panel-body">
          <div class="form-group">
            <%= label_tag :product_vendor, "Vendor", :class => "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= text_field_tag :product_vendor,nil, :class => "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <%= label_tag :product_type, "Type", :class => "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= text_field_tag :product_type,nil, :class => "form-control" %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="panel panel-info">
        <div class="panel-heading">Product Price</div>
        <div class="panel-body">
          <div class="form-group">
            <%= label_tag :product_price, "Price", :class => "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <div class="input-group">
                <%= number_field_tag :product_price,nil, :placeholder => "00.00", :class => "form-control", :required => true %>
                <span class="input-group-addon">
                  <%= @thisshop.currency %>
                </span>
              </div>
            </div>
          </div>
          <div class="form-group">
            <%= label_tag :product_compare_price, "Compare at price", :class => "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <div class="input-group">
                <%= number_field_tag :product_compare_price,nil, :placeholder => "00.00", :class => "form-control" %>
                <span class="input-group-addon">
                  <%= @thisshop.currency %>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12">
      <div class="panel panel-info">
        <div class="panel-heading">Images</div>
        <div class="panel-body">
          <script id="image-template" type="text/x-handlebars-template">
            <div class="form-group">
              <label for="product_image[{{i}}]" class="col-sm-2 control-label">Image URL</label>
              <div class="col-sm-10">
                <div class="input-group">
                  <input type="url" name="product_image[{{i}}]" id="product_image[{{i}}]" class="form-control">
                  <span class="input-group-btn">
                    <button class="btn btn-danger remove" type="button"><i class="fa fa-times"></i></button>
                  </span>
                </div><!-- /input-group -->
              </div>
            </div>
          </script>
          <div id="productImages"></div>
          <button id="addProductImage" type="button" class="btn btn-primary">Add Image</button>
        </div>
      </div>
    </div>

    <div class="col-xs-12">
      <div class="panel panel-info">
        <div class="panel-heading">Variants</div>
        <div class="panel-body variants-panel">
          <script id="variant-template" type="text/x-handlebars-template">
            <div class="variant ">
              <h5>Variant</h5>
              <div class="clearfix">
                <div class="col-xs-12 col-sm-4">
                  <div class="form-group">
                    <input type="text" name="product_variant[{{i}}][option_1]" id="product_variant[{{i}}][option_1]" placeholder="Option 1 *" class="form-control pvalue-1" required="required">
                  </div>
                </div>
                <div class="col-xs-12 col-sm-4">
                  <div class="form-group">
                    <input type="text" name="product_variant[{{i}}][option_2]" id="product_variant[{{i}}][option_2]" placeholder="Option 2" class="form-control pvalue-2" required="required"  >
                  </div>
                </div>
                <div class="col-xs-12 col-sm-4">
                  <div class="form-group">
                    <input type="text" name="product_variant[{{i}}][option_3]" id="product_variant[{{i}}][option_3]" placeholder="Option 3" class="form-control pvalue-3" required="required"  >
                  </div>
                </div>
                <div class="col-xs-12 col-sm-4">
                  <div class="form-group">
                    <div class="input-group">
                      <input type="text" name="product_variant[{{i}}][price]" id="product_variant[{{i}}][price]" placeholder="Price" class="form-control" required="required" >
                      <span class="input-group-addon">
                        <%= @thisshop.currency %>
                      </span>
                    </div>
                  </div>
                </div>
                <div class="col-xs-12 col-sm-4">
                  <div class="form-group">
                    <div class="input-group">
                      <input type="text" name="product_variant[{{i}}][compare_at_price]" id="product_variant[{{i}}][compare_at_price]" placeholder="Compare at price" class="form-control" >
                      <span class="input-group-addon">
                        <%= @thisshop.currency %>
                      </span>
                    </div>
                  </div>
                </div>
                <div class="col-xs-12 col-sm-4 text-center">
                  <div class="form-group">
                    <button type="button" class="remove btn btn-fab btn-danger btn-fab-mini"><i class="fa fa-times"></i></button>
                  </div>
                </div>
              </div>
            </div>
          </script>
          <div id="productOptions">
            <h5>Options</h5>
            <div class="clearfix">
              <div class="col-xs-12 col-sm-4">
                <div class="form-group">
                  <label for="product_options[1]" class="control-label">Option 1</label>
                  <input type="text" name="product_options[1]" id="product_options_1" placeholder="Color, Size" class="form-control">
                </div>
              </div>
              <div class="col-xs-12 col-sm-4">
                <div class="form-group">
                  <label for="product_options[2]" class="control-label">Option 2</label>
                  <input type="text" name="product_options[2]" id="product_options_2" placeholder="Color, Size" class="form-control">
                </div>
              </div>
              <div class="col-xs-12 col-sm-4">
                <div class="form-group">
                  <label for="product_options[3]" class="control-label">Option 3</label>
                  <input type="text" name="product_options[3]" id="product_options_3" placeholder="Color, Size" class="form-control">
                </div>
              </div>
            </div>
          </div>
          <div id="productVariants"></div>
          <button id="addVariant" type="button" class="btn btn-primary btn-fab-mini btn-fab"><i class="fa fa-plus"></i></button>
        </div>
      </div>
    </div>

    <div class="col-xs-12">
      <%= submit_tag :Add, :class => "btn btn-info pull-right" %>
    </div>
    <% end %>
  </div>
</div><script>
$(document).on("turbolinks:load",function() {
  tinymce.remove();
  tinyMCE.init({
    selector: "textarea.tinymce",
    toolbar: "bold, italic, underline strikethrough | alignleft, aligncenter, alignright, alignjustify | styleselect, formatselect, fontsizeselect | bullist, numlist, blockquote",
    theme: "modern",
    skin: "light",
    menubar: false
  });

  var imagesource   = $("#image-template").html();
  var imagetemplate = Handlebars.compile(imagesource);
  var newImageBtn = $("#addProductImage");

  window.imageCounter = 0;
  newImageBtn.unbind("click").off("click");
  newImageBtn.on("click",function(e){
    e.preventDefault();
    window.imageCounter++;
    var newImage = $(imagetemplate({i: window.imageCounter }));
    newImage.find(".remove").on("click",function(){
      $(this).closest(".form-group").remove();
    });
    $("#productImages").append(newImage);
  });

  var variantSource   = $("#variant-template").html();
  var variantTemplate = Handlebars.compile(variantSource);
  var newVariantBtn = $("#addVariant");
  var poption1 = $("#product_options_1"),
      poption2 = $("#product_options_2"),
      poption3 = $("#product_options_3");
  var productOptions = $("#productOptions").show();

  window.variantICounter = 0;
  window.variantCounter = 0;
  newVariantBtn.unbind("click").off("click");
  newVariantBtn.on("click",function(e){
    e.preventDefault();


    // creating variables
    var val1 = poption1.val(),
        val2 = poption2.val(),
        val3 = poption3.val();

    // if variant limit is exceeded
    if( window.variantICounter > 99 ){
      ShopifyApp.flashError("Variants Limit Reached ");
      return;
    }

    // if no options are entered, then display an error
    if( val1 == ""){
      ShopifyApp.flashError("Please add options first.");
      return ;
    }

    // incrementing variants counter
    window.variantCounter++;
    window.variantICounter++;

    // hide the options box
    productOptions.hide();

    // creating new variant
    var newVariant = $(variantTemplate({i: window.variantCounter }));
    newVariant.find(".remove").on("click",function(){
      $(this).closest(".variant").remove();
      window.variantICounter--;

      if( $("#productVariants").find(".variant").length < 1){
        window.variantCounter = 0;
        window.variantICounter = 0;
        productOptions.show();
      }
    });

    // appending the new variant
    $("#productVariants").append(newVariant);

    // initializing the inputs with options
    if( val1 != ""){
      newVariant.find(".pvalue-1").first().attr("placeholder", val1 );

      if( val2 != ""){
        newVariant.find(".pvalue-2").first().attr("placeholder", val2 );

        if( val3 != ""){
          newVariant.find(".pvalue-3").first().attr("placeholder", val3 );
        }
        else{
          newVariant.find(".pvalue-3").first().closest(".form-group").closest("div").remove();
        }
      }
      else{
        newVariant.find(".pvalue-2").first().closest(".form-group").closest("div").remove();
        newVariant.find(".pvalue-3").first().closest(".form-group").closest("div").remove();

      }
    }
    else{
      newVariant.find(".pvalue-1").first().closest(".form-group").closest("div").remove();
      newVariant.find(".pvalue-2").first().closest(".form-group").closest("div").remove();
      newVariant.find(".pvalue-3").first().closest(".form-group").closest("div").remove();


    }


    ShopifyApp.flashNotice("Variant Added");
    console.log(window.variantICounter);
  });
});
</script>

app/views/product/choose_image.html.erb
<div class="container-fluid">
  <div class="row">
    <% for image in @product.images %>
    <div class="col-xs-4 col-sm-3">
      <div class="img-choice-wrapper">
        <img src="<%= image.src %>" data-id="<%= image.id %>" alt="" class="img-thumbnail">
      </div>
    </div>
    <% end %>
  </div>
</div>
<script>
  $(document).on("turbolinks:load",function(){
    var image_input = $("#image_src");
    $(".img-choice-wrapper img").on("click",function(){
      var src = $(this).attr("src");
      image_input.val(src);

      $(".img-choice-wrapper img").removeClass("selected");
      $(this).addClass("selected");
    });
  });
</script>
<form method="POST" action="<%= save_image_path %>" id="chooseImageForm" data-remote="true">
  <input type="hidden" name="product_id" value="<%= @product.id %>">
  <input type="hidden" name="image_src" id="image_src" value="">
</form>
<style>
  .img-choice-wrapper {
      height: 130px;
      margin-top: 10px;
  }
  .img-choice-wrapper img {
      object-fit: contain;
      height: 100%;
      width: 100%;
      background: none;
      cursor: pointer;
  }
  .img-choice-wrapper img.img-thumbnail.selected{
    border-color: #5967c3;
  }
</style>

app/views/product/enter_image_url.html.erb
<div class="container-fluid">
  <div class="row">
    <% if @image %>
    <div class="col-xs-12">
      <div class="img-choice-wraper">
        <img src="<%= @image %>" alt="">
      </div>
    </div>
    <% end %>
    <div class="col-xs-12">
      <form method="POST" action="<%= save_image_path %>" id="chooseImageForm" data-remote="true">
        <input type="hidden" name="product_id" value="<%= @product.id %>">
        <div class="form-group mt-2">
          <label for="image_src">Enter URL here:</label>
          <input type="url" class="form-control" placeholder="http://url-goes-here.com" name="image_src" id="image_src" value="<%= @image %>">
        </div>
      </form>
    </div>
  </div>
</div>
<style>
  .img-choice-wrapper {
      height: 130px;
      margin-top: 10px;
  }
  .img-choice-wrapper img {
      object-fit: contain;
      height: 100%;
      width: 100%;
      background: none;
      cursor: pointer;
  }
  .img-choice-wrapper img.img-thumbnail.selected{
    border-color: #5967c3;
  }
</style>

app/views/product/remove.js.erb
ShopifyApp.flashNotice("Product deleted succesfully.");
$("tr.product-<%= @classid %>").addClass("animated").addClass("zoomOutRight");
setTimeout(function(){
  $("tr.product-<%= @classid %>").remove();
},1000);

app/views/product/save_image.js.erb
<% if @success %>
ShopifyApp.flashNotice("Image selected successfully.");
var app = ShopifyApp.window();
app.$("body").find(".image-<%= @product.id %>").first().removeClass("hidden").next("span.text-danger").remove();
app.$("body").find(".image-<%= @product.id %> img").first().attr("src","<%= params[:image_src] %>");
<% end %>
ShopifyApp.Modal.close();